const HYPOTHESIS_TOKEN = "__SHOPHEBEL_CONVERSION_HYPOTHESE__";

export const REPORT_LABELS = {
  premiumReportTitle: "Dein Premium-Report",
  executiveSnapshot: "Kurzüberblick",
  websiteIntelligenceScore: "Shophebel-Analysewert",
  visualAudit: "Visuelle Analyse",
  screenshotIntelligenceConsole: "Visueller Seitenüberblick",
  fullPageScreenshot: "Gesamte Seitenansicht",
  desktopScreenshot: "Desktop-Ansicht",
  mobileScreenshot: "Mobile Ansicht",
  heroScreenshot: "Startbereich",
  capture: "Erfasste Ansicht",
  score: "Bewertung",
  status: "Einschätzung",
  plan: "Fahrplan",
  priorityScore: "Prioritätswert",
  managementSummary: "Management-Zusammenfassung",
  premiumStrategy: "Premium-Strategie",
  visualCheck: "Visuelle Prüfung",
  sevenDayPlan: "7-Tage-Fahrplan",
  measuresPlan: "Priorisierter Maßnahmenplan",
};

export const CUSTOMER_FORBIDDEN_REPORT_LABELS = [
  "Executive Snapshot",
  "Executive Summary",
  "Website Intelligence Score",
  "Visual Audit",
  "Screenshot Intelligence Console",
  "Full Page Screenshot",
  "Visual Capture",
  "Intelligence Score",
  "Screenshot Intelligence",
  "Visual Intelligence",
  "Full Visual Audit",
  "Premium Strategy Layer",
  "Executive Recommendations",
  "Business Priorities",
  "7-Day Action Plan",
  "Top Issues",
  "Report Snapshot",
];

export const CUSTOMER_FORBIDDEN_ASCII_UMLAUTS = [
  "Bildverstaendnis",
  "Kontaktmoeglichkeiten",
  "verschluesselte",
  "Schriftgroessen",
  "groesser",
  "zuruecknehmen",
  "Massnahmen",
  "Massnahme",
  "verfuegbar",
  "vollstaendige",
  "ausfuehren",
  "fuer",
  "Fuehrung",
  "fuehren",
  "fuehrt",
  "Einfuehrung",
  "Uebersicht",
  "Pruefung",
  "pruefen",
  "Spaeter",
  "naechste",
  "naechsten",
  "naechster",
  "Nutzerfuehrung",
  "Erklaerung",
  "zusaetzliche",
  "Prioritaet",
  "Prioritaeten",
];

const COPY_REPLACEMENTS: Array<[RegExp, string]> = [
  [/ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¼|ÃƒÆ’Ã‚Â¼|ÃƒÂ¼/g, "ü"],
  [/Ã¼/g, "ü"],
  [/ÃƒÆ’Ã†â€™Ãƒâ€¦Ã¢â‚¬Å“|ÃƒÆ’Ã…â€œ|ÃƒÅ“/g, "Ü"],
  [/Ãœ/g, "Ü"],
  [/ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¶|ÃƒÆ’Ã‚Â¶|ÃƒÂ¶/g, "ö"],
  [/Ã¶/g, "ö"],
  [/ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“|ÃƒÆ’Ã¢â‚¬â€œ|Ãƒâ€“/g, "Ö"],
  [/Ã–/g, "Ö"],
  [/ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¤|ÃƒÆ’Ã‚Â¤|ÃƒÂ¤/g, "ä"],
  [/Ã¤/g, "ä"],
  [/ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾|ÃƒÆ’Ã¢â‚¬Å¾|Ãƒâ€ž/g, "Ä"],
  [/Ã„/g, "Ä"],
  [/ÃƒÆ’Ã†â€™Ãƒâ€¦Ã‚Â¸|ÃƒÆ’Ã†â€™Ãƒâ€šÃ…Â¸|ÃƒÆ’Ã…Â¸|ÃƒÅ¸/g, "ß"],
  [/ÃŸ/g, "ß"],
  [/Ãƒâ€šÃ‚Â·|Ã‚Â·/g, "·"],
  [/Executive Snapshot/gi, REPORT_LABELS.executiveSnapshot],
  [/Executive Summary/gi, REPORT_LABELS.managementSummary],
  [/Website Intelligence Score/gi, REPORT_LABELS.websiteIntelligenceScore],
  [/Screenshot Intelligence Console/gi, REPORT_LABELS.screenshotIntelligenceConsole],
  [/Full Page Screenshot/gi, REPORT_LABELS.fullPageScreenshot],
  [/Desktop Screenshot/gi, REPORT_LABELS.desktopScreenshot],
  [/Mobile Screenshot/gi, REPORT_LABELS.mobileScreenshot],
  [/Hero Screenshot/gi, REPORT_LABELS.heroScreenshot],
  [/Visual Capture/gi, "Visuelle Ansicht"],
  [/\bCapture\b/gi, REPORT_LABELS.capture],
  [/Visual Audit Notes/gi, REPORT_LABELS.visualCheck],
  [/Visual Audit/gi, REPORT_LABELS.visualAudit],
  [/Intelligence Score/gi, REPORT_LABELS.websiteIntelligenceScore],
  [/Screenshot Intelligence/gi, REPORT_LABELS.screenshotIntelligenceConsole],
  [/Visual Intelligence/gi, REPORT_LABELS.visualAudit],
  [/Full Visual Audit/gi, "Vollständige visuelle Analyse"],
  [/Premium Strategy Layer/gi, "Strategische Premium-Ebene"],
  [/Executive Recommendations/gi, "priorisierte Empfehlungen"],
  [/Business Priorities/gi, "geschäftliche Prioritäten"],
  [/7-Day Action Plan/gi, REPORT_LABELS.sevenDayPlan],
  [/Report Snapshot/gi, "Report-Auszug"],
  [/Top Issues/gi, "Wichtigste Probleme"],
  [/Premium Conversion- und Trust-Audit/gi, "Premium Anfrage- und Vertrauens-Audit"],
  [/Conversion-Hebel/gi, "Anfrage- und Kaufhebel"],
  [/Conversion Hypothese/gi, "Conversion-Hypothese"],
  [/Above the fold/gi, "sichtbarer Startbereich"],
  [/oberhalb der Falz/gi, "im sichtbaren Startbereich"],
  [/Revenue Blockers/gi, "Umsatzbremsen"],
  [/Top Umsatzblocker/gi, "Top-Umsatzbremsen"],
  [/Conversion Quick Wins/gi, "Sofortmaßnahmen für mehr Anfragen"],
  [/Quick Wins/gi, "schnelle Verbesserungen"],
  [/Opportunity Roadmap/gi, REPORT_LABELS.measuresPlan],
  [/Opportunities/gi, "Potenziale"],
  [/Opportunity/gi, "Potenzial"],
  [/Shophebel-Modul/gi, "Empfohlener Umsetzungspfad"],
  [/\bSuggested Service\b/gi, "Empfohlene Begleitung"],
  [/\bExpected Effect\b/gi, "Erwarteter Effekt"],
  [/\bBusiness Impact\b/gi, "Geschäftliche Wirkung"],
  [/\bCall-to-Action\b/gi, "Handlungsaufforderung"],
  [/\bCTA\b/g, "Button"],
  [/\bTrust\b/g, "Vertrauen"],
  [/\bConversion\b/gi, "Anfrage-/Kaufwahrscheinlichkeit"],
];

const UMLAUT_WORD_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bAbschluesse\b/gi, "Abschlüsse"],
  [/\bAbschluessen\b/gi, "Abschlüssen"],
  [/\bAbbrueche\b/gi, "Abbrüche"],
  [/\bAbstaende\b/gi, "Abstände"],
  [/\bAenderung\b/gi, "Änderung"],
  [/\bAenderungen\b/gi, "Änderungen"],
  [/\bBildverstaendnis\b/gi, "Bildverständnis"],
  [/\bEinfuehrung\b/gi, "Einführung"],
  [/\bEinschaetzung\b/gi, "Einschätzung"],
  [/\bergaenzt\b/gi, "ergänzt"],
  [/\bergaenzte\b/gi, "ergänzte"],
  [/\berklaert\b/gi, "erklärt"],
  [/\bErklaerung\b/gi, "Erklärung"],
  [/\berklaeren\b/gi, "erklären"],
  [/\bklaeren\b/gi, "klären"],
  [/\bfuer\b/gi, "für"],
  [/\bFuehrung\b/g, "Führung"],
  [/\bfuehren\b/gi, "führen"],
  [/\bfuehrt\b/gi, "führt"],
  [/\bfuehrend\b/gi, "führend"],
  [/\bFuehre\b/g, "Führe"],
  [/\bfrueher\b/gi, "früher"],
  [/\bFormularnaehe\b/gi, "Formularnähe"],
  [/\bGeraeten\b/gi, "Geräten"],
  [/\bgeoeffnet\b/gi, "geöffnet"],
  [/\bgedrueckt\b/gi, "gedrückt"],
  [/\bgeprueft\b/gi, "geprüft"],
  [/\bgepruefte\b/gi, "geprüfte"],
  [/\bgepruefter\b/gi, "geprüfter"],
  [/\bgroesser\b/gi, "größer"],
  [/\bgroessere\b/gi, "größere"],
  [/\bgroesste\b/gi, "größte"],
  [/\bGroesse\b/g, "Größe"],
  [/\bhoeherer\b/gi, "höherer"],
  [/\bkoennen\b/gi, "können"],
  [/\bkoennte\b/gi, "könnte"],
  [/\bkuerzer\b/gi, "kürzer"],
  [/\blaenger\b/gi, "länger"],
  [/\bMassnahmen\b/g, "Maßnahmen"],
  [/\bMassnahme\b/g, "Maßnahme"],
  [/\bmoeglich\b/gi, "möglich"],
  [/\bKontaktmoeglichkeiten\b/gi, "Kontaktmöglichkeiten"],
  [/\bnaechsten\b/gi, "nächsten"],
  [/\bnaechste\b/gi, "nächste"],
  [/\bnaechster\b/gi, "nächster"],
  [/\bnaechstem\b/gi, "nächstem"],
  [/\bNutzerfuehrung\b/g, "Nutzerführung"],
  [/\boeffnet\b/gi, "öffnet"],
  [/\bPrio(?:ri)?taet\b/gi, "Priorität"],
  [/\bPrio(?:ri)?taeten\b/gi, "Prioritäten"],
  [/\bprimaeren\b/gi, "primären"],
  [/\bPruefung\b/gi, "Prüfung"],
  [/\bPruefe\b/gi, "Prüfe"],
  [/\bpruefen\b/gi, "prüfen"],
  [/\bRueckgabe\b/gi, "Rückgabe"],
  [/\bschaerfen\b/gi, "schärfen"],
  [/\bSchriftgroessen\b/gi, "Schriftgrößen"],
  [/\bSpaeter\b/g, "Später"],
  [/\bstoert\b/gi, "stört"],
  [/\bstaerker\b/gi, "stärker"],
  [/\bstaerken\b/gi, "stärken"],
  [/\bStaerken\b/g, "Stärken"],
  [/\bUebersicht\b/gi, "Übersicht"],
  [/\bUeberschriften\b/gi, "Überschriften"],
  [/\buebersetzen\b/gi, "übersetzen"],
  [/\bverschluesselte\b/gi, "verschlüsselte"],
  [/\bVerstaendlichkeit\b/gi, "Verständlichkeit"],
  [/\bVerstaendnis\b/gi, "Verständnis"],
  [/\bverfuegbar\b/gi, "verfügbar"],
  [/\bvollstaendig\b/gi, "vollständig"],
  [/\bvollstaendige\b/gi, "vollständige"],
  [/\bausfuehren\b/gi, "ausführen"],
  [/\bzusaetzliche\b/gi, "zusätzliche"],
  [/\bzuruecknehmen\b/gi, "zurücknehmen"],
  [/\bzoegern\b/gi, "zögern"],
];

function protectAllowedLabels(text: string) {
  return text.replace(/Conversion-Hypothese/gi, HYPOTHESIS_TOKEN);
}

function restoreAllowedLabels(text: string) {
  return text.replace(new RegExp(HYPOTHESIS_TOKEN, "g"), "Conversion-Hypothese");
}

export function normalizeGermanReportText(value: unknown, fallback = "") {
  if (typeof value !== "string") {
    return fallback;
  }

  const protectedText = protectAllowedLabels(value.trim());
  const normalized = [...COPY_REPLACEMENTS, ...UMLAUT_WORD_REPLACEMENTS].reduce(
    (text, [pattern, replacement]) => text.replace(pattern, replacement),
    protectedText,
  )
    .replace(/\b(Der wahrscheinlich größte Bremsfaktor ist) ([A-ZÄÖÜ])/g, "$1: $2")
    .replace(/\s+/g, " ")
    .replace(/\s+([,.;:!?])/g, "$1")
    .replace(/\.{2,}/g, ".")
    .trim();

  return restoreAllowedLabels(normalized);
}

export function hasForbiddenCustomerReportText(text: string) {
  const normalized = normalizeGermanReportText(text);
  return [...CUSTOMER_FORBIDDEN_REPORT_LABELS, ...CUSTOMER_FORBIDDEN_ASCII_UMLAUTS].some((term) =>
    normalized.includes(term),
  );
}
